### ISSUE TITLE
Value Web Tool doesn't differentiate New Value Web vs New Opposition Value. 

### ISSUE THREAD

**Issue by ryanreso1993** [Soyle-Productions/soyle-stories-desktop#74]
1. Given that a user has opened Character Value Comparison
And the user has created new value webs and new opposition values with two characters
When the user clicks Add Value

**Expected result**
Then the user should be able to see a difference between value webs and opposition values.

**Actual result**
The user cannot tell what values are oppositions.

![image](https://user-images.githubusercontent.com/61167122/100029081-a5409f80-2dad-11eb-987a-fb8fcf5b7abf.png)

**Comment by b-camphart** [comment]
@ryanreso1993 can you take another look at this?

**Comment by b-camphart** [comment]
@ryanreso1993 bumping this issue

**Comment by ryanreso1993** [comment]
Okay let me try to reproduce my steps:
1. Create a project
2. Create two characters
3. Open the Themes tab from the top menu bar
4. Create a theme
5. Right click the theme and open Compare Character Values
6. Add the two characters to the Comparison tool
7. Create a Value for the first character
8. Create an Oppositional value for that character
9. Add the first character's opposition value as the value for the second character

What I expect: That there is a visible way to tell which character values and opposes a theme.

Actual result: When you add the second character's value, although it is the first character's oppositional value, the value and its opposition appear the same. In the example below, there is no way to visibly tell that Bad Cop values Personal Code and opposes Law Abiding, and that Good Cop values Law Abiding and opposes Personal Code:

![image](https://user-images.githubusercontent.com/61167122/128270163-ebbafb7d-37df-4d19-b944-f253ce32b9d5.png)


Does that help?

**Comment by b-camphart** [comment]
I think what you're looking for here is a way to specify that two characters are _aligned_ and thus share a particular value in a value web or that two (or more) characters are opposed and thus have different values from a particular value web.  Two characters may be aligned in some ways, yet opposed in others.  The way the tool is designed now, the user has to make that inference by listing which values the characters have for each value web.  If someone isn't quite familiar with the concept, this can obviously be confusing.  I think this is worth exploring as a potential redesign of this tool in the future.

**Comment by b-camphart** [comment]
See #110
