### ISSUE TITLE
Creating a New Location in Link Location Base Story Structure Doesn't Automatically Link to Location

### ISSUE THREAD

**Issue by ryanreso1993** [Soyle-Productions/soyle-stories-desktop#89]
Creating a New Location in Link Location Base Story Structure Doesn't Automatically Link to Location

    1. Open a project
    2. Create a Character and a Character Arc for the Character
    3. Open the Base Story Structure Tool
    4. Select Linked Location Drop Down 
    5. Select Create Location and Create a Location

Expected Result: The new Location is created and will be listed as Linked in the Base Story Structure. 
Actual Result: The new Location is created but is not listed as Linked in the Base Story Structure.

**Comment by b-camphart** [comment]
The Base Story Structure Tool will need to be re-worked when we revisit character arcs and themes.  It's no longer accessible.
