### ISSUE TITLE
Theme Rename Not Updating In Select Existing Theme in Create New Symbol in the Scene Tool

### ISSUE THREAD

**Issue by ryanreso1993** [Soyle-Productions/soyle-stories-desktop#90]
1. Create a project
2. Create a Scene, A Character, and a Character Arc
3. Rename the Character Arc
4. Open Track Symbols in the Scene
5. Select the drop down for Select Existing Theme

What I expect: The Character Arc will show the updated name. 
What actually happens: The Character Arc name isn't updated.

**Comment by b-camphart** [comment]
Renaming character arcs is no longer possible, only themes.  Due to this, this bug is no longer re-creatable as of v0.1.13-alpha.
